### ISSUE TITLE
md→htmlできるjs作ればtopicをmdで書けて楽なのではないかという話

### ISSUE THREAD

**Issue by AyagawaP** [AyaExpTech/web#4]
タイトルの通り。使える記法に制限かけてもいいのでmdとかを使えるようにしたい。

**Comment by Fill-Amato** [comment]
それにすると文字色とかのプロパティいじれなくないですか

**Comment by AyagawaP** [comment]
たしかにそうじゃんやーめよ

**Comment by AyagawaP** [comment]
文字色プロパティ、いじらなくてよくない？と思いました
有名なサイトとかも見たんですけどmdで表現できる範囲で十分だなぁとなったのでこの方針で行きます

**Comment by Tiamat-KIT** [comment]
OK
